TOKEN_API: "api-ce.kroger.com/v1/connect/oauth2/token"
CLIENT_ID: "grampsmarket-b1b6dd2ff88a5c7a0b5b88ee2d40ac9a6171680135351100340"
CLIENT_SECRET: "x0wOaFLyzCxA0bDt9gyoxunjhKKqhTZ6msEUDmN1"
PRODUCT_API: "api-ce.kroger.com/v1/products"
AUTH_KEY: "Basic Z3JhbXBzbWFya2V0LWIxYjZkZDJmZjg4YTVjN2EwYjViODhlZTJkNDBhYzlhNjE3MTY4MDEzNTM1MTEwMDM0MDp4MHdPYUZMeXpDeEEwYkR0OWd5b3h1bmpoS0txaFRaNm1zRVVEbU4x"